import Head from "next/head";
import Image from "next/image";
import fetchVacations from "../components/fetchVacations";
import { useQuery } from "@tanstack/react-query";

export default function Home() {
  const displayVacations = async () => {
    const responce = await fetchVacations();
    return responce;
  };

  const { data, isLoading, error } = useQuery(["vacations"], displayVacations);

  if (isLoading) return <div>Loading</div>;
  if (error) return <div>Error</div>;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data?.fetchedVacations.map((vacation: any, index: number) => (
          <div key={index}>
            <div>{vacation.city}</div>
            <div>{vacation.description}</div>
            <div>
              {vacation.imageCollection.items.map(
                (image: any, index: number) => {
                  return (
                    <div key={index}>
                      <img src={image.url} className="image" />
                    </div>
                  );
                }
              )}
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
