import Head from "next/head";
import Image from "next/image";
import fetchVacations from "../components/fetchVacations";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";

export default function Home() {
  const { data, isLoading, error } = useQuery(
    ["vacation-cities"],
    fetchVacations
  );

  if (isLoading) return <div>Loading</div>;
  if (error) return <div>Error</div>;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data?.fetchedVacations.map((vacation: any, index: number) => (
          <div key={index}>
            <Link href={`/vacations/${vacation.city}`}>{vacation.city}</Link>
            <div>{vacation.description}</div>
            {/* <div>
              {vacation.imageCollection.items.map(
                (image: any, index: number) => {
                  return (
                    <div key={index}>
                      <img src={image.url} className="image" />
                    </div>
                  );
                }
              )}
            </div> */}
          </div>
        ))}
      </div>
    </>
  );
}
